### ISSUE TITLE
air-adb: adb not found in /home/dream71/Android/Sdk/platform-tools/adb

### ISSUE THREAD

**Issue by ImaginativeShohag** [felHR85/Air-Adb-Plugin#1]
**Error:**
`Air-Adb: Something went wrong (execution of script failed : air-adb: adb not found in /home/dream71/Android/Sdk/platform-tools/adb)`

This is not my SDK location. I don't find any settings in the Air-Adb to set my SDK location.

**Comment by felHR85** [comment]
@ImaginativeShohag Thank you for the report. I must implement a way for easily specify your actual SDK location if it is not installed in the default folder.
In the meantime you could edit the script that is generated by Air-Adb in ~/.air-adb/air-adb.sh line 6:
```
LINUX_ADB_DEFAULT_PATH=~/Android/Sdk/platform-tools/adb
```

**Comment by felHR85** [comment]
This one-liners could be useful:
```shell
#For OSX use this one-liner changing my_path with your current path
MY_PATH="my_path" && ex -sc "6d|x" ~/.air-adb/air-adb.sh && ex -sc "6i|OSX_ADB_DEFAULT_PATH=$MY_PATH" -cx ~/.air-adb/air-adb.sh

#For Linux use this one-liner changing my_path with your current path
MY_PATH="my_path" && ex -sc "7d|x" ~/.air-adb/air-adb.sh && ex -sc "7i|LINUX_ADB_DEFAULT_PATH=$MY_PATH" -cx ~/.air-adb/air-adb.sh

```
